// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Welcome.proto

package welcome

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	player "github.com/project-quiz/quiz-go-model/Player"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Welcome struct {
	Player               *player.Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Welcome) Reset()         { *m = Welcome{} }
func (m *Welcome) String() string { return proto.CompactTextString(m) }
func (*Welcome) ProtoMessage()    {}
func (*Welcome) Descriptor() ([]byte, []int) {
	return fileDescriptor_d057ebb5498c6f32, []int{0}
}

func (m *Welcome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Welcome.Unmarshal(m, b)
}
func (m *Welcome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Welcome.Marshal(b, m, deterministic)
}
func (m *Welcome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Welcome.Merge(m, src)
}
func (m *Welcome) XXX_Size() int {
	return xxx_messageInfo_Welcome.Size(m)
}
func (m *Welcome) XXX_DiscardUnknown() {
	xxx_messageInfo_Welcome.DiscardUnknown(m)
}

var xxx_messageInfo_Welcome proto.InternalMessageInfo

func (m *Welcome) GetPlayer() *player.Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterType((*Welcome)(nil), "Data.Welcome")
}

func init() { proto.RegisterFile("Welcome.proto", fileDescriptor_d057ebb5498c6f32) }

var fileDescriptor_d057ebb5498c6f32 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0d, 0x4f, 0xcd, 0x49,
	0xce, 0xcf, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x71, 0x49, 0x2c, 0x49, 0x94,
	0xe2, 0x09, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x82, 0x88, 0x29, 0xe9, 0x73, 0xb1, 0x43, 0x15, 0x09,
	0xa9, 0x70, 0xb1, 0x15, 0x80, 0xa5, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x78, 0xf4, 0x40,
	0xea, 0xf5, 0x20, 0xca, 0x83, 0xa0, 0x72, 0x49, 0x6c, 0x60, 0x7d, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc3, 0x52, 0x40, 0x22, 0x5c, 0x00, 0x00, 0x00,
}
