// Code generated by protoc-gen-go. DO NOT EDIT.
// source: question.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	Guid                 string    `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Question             string    `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answers              []*Answer `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_64d310e1b23c85d7, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Question) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Question) GetAnswers() []*Answer {
	if m != nil {
		return m.Answers
	}
	return nil
}

func init() {
	proto.RegisterType((*Question)(nil), "model.Question")
}

func init() { proto.RegisterFile("question.proto", fileDescriptor_64d310e1b23c85d7) }

var fileDescriptor_64d310e1b23c85d7 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2c, 0x4d, 0x2d,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49,
	0xcd, 0x91, 0xe2, 0x49, 0xcc, 0x2b, 0x2e, 0x4f, 0x2d, 0x82, 0x08, 0x2a, 0x25, 0x73, 0x71, 0x04,
	0x42, 0x95, 0x09, 0x09, 0x71, 0xb1, 0xa4, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x81, 0xd9, 0x42, 0x52, 0x5c, 0x1c, 0x30, 0x63, 0x24, 0x98, 0xc0, 0xe2, 0x70, 0xbe, 0x90,
	0x3a, 0x17, 0x3b, 0xc4, 0xac, 0x62, 0x09, 0x66, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x5e, 0x3d, 0xb0,
	0x15, 0x7a, 0x8e, 0x60, 0xd1, 0x20, 0x98, 0x6c, 0x12, 0x1b, 0xd8, 0x2e, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x54, 0x94, 0x08, 0x92, 0x00, 0x00, 0x00,
}
