// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Player/Player.proto

package Data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2feffaaeb26e76c, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type PlayerJoined struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Player               *Player  `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerJoined) Reset()         { *m = PlayerJoined{} }
func (m *PlayerJoined) String() string { return proto.CompactTextString(m) }
func (*PlayerJoined) ProtoMessage()    {}
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2feffaaeb26e76c, []int{1}
}

func (m *PlayerJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoined.Unmarshal(m, b)
}
func (m *PlayerJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoined.Marshal(b, m, deterministic)
}
func (m *PlayerJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoined.Merge(m, src)
}
func (m *PlayerJoined) XXX_Size() int {
	return xxx_messageInfo_PlayerJoined.Size(m)
}
func (m *PlayerJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoined.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoined proto.InternalMessageInfo

func (m *PlayerJoined) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerJoined) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type PlayerLeft struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Player               *Player  `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLeft) Reset()         { *m = PlayerLeft{} }
func (m *PlayerLeft) String() string { return proto.CompactTextString(m) }
func (*PlayerLeft) ProtoMessage()    {}
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2feffaaeb26e76c, []int{2}
}

func (m *PlayerLeft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLeft.Unmarshal(m, b)
}
func (m *PlayerLeft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLeft.Marshal(b, m, deterministic)
}
func (m *PlayerLeft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLeft.Merge(m, src)
}
func (m *PlayerLeft) XXX_Size() int {
	return xxx_messageInfo_PlayerLeft.Size(m)
}
func (m *PlayerLeft) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLeft.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLeft proto.InternalMessageInfo

func (m *PlayerLeft) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerLeft) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type PlayersNickNameChanged struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Player               *Player  `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayersNickNameChanged) Reset()         { *m = PlayersNickNameChanged{} }
func (m *PlayersNickNameChanged) String() string { return proto.CompactTextString(m) }
func (*PlayersNickNameChanged) ProtoMessage()    {}
func (*PlayersNickNameChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2feffaaeb26e76c, []int{3}
}

func (m *PlayersNickNameChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersNickNameChanged.Unmarshal(m, b)
}
func (m *PlayersNickNameChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersNickNameChanged.Marshal(b, m, deterministic)
}
func (m *PlayersNickNameChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersNickNameChanged.Merge(m, src)
}
func (m *PlayersNickNameChanged) XXX_Size() int {
	return xxx_messageInfo_PlayersNickNameChanged.Size(m)
}
func (m *PlayersNickNameChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersNickNameChanged.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersNickNameChanged proto.InternalMessageInfo

func (m *PlayersNickNameChanged) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayersNickNameChanged) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "Data.Player")
	proto.RegisterType((*PlayerJoined)(nil), "Data.PlayerJoined")
	proto.RegisterType((*PlayerLeft)(nil), "Data.PlayerLeft")
	proto.RegisterType((*PlayersNickNameChanged)(nil), "Data.PlayersNickNameChanged")
}

func init() { proto.RegisterFile("Player/Player.proto", fileDescriptor_a2feffaaeb26e76c) }

var fileDescriptor_a2feffaaeb26e76c = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0e, 0xc8, 0x49, 0xac,
	0x4c, 0x2d, 0xd2, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x2e, 0x89, 0x25,
	0x89, 0x4a, 0x32, 0x5c, 0x6c, 0x10, 0x51, 0x21, 0x21, 0x2e, 0x96, 0xf4, 0xd2, 0xcc, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc9, 0x85, 0x8b, 0x07, 0x22, 0xeb, 0x95, 0x9f,
	0x99, 0x97, 0x9a, 0x22, 0xc4, 0xc7, 0xc5, 0x04, 0x55, 0xc1, 0x1a, 0xc4, 0x94, 0x99, 0x22, 0xa4,
	0xc2, 0xc5, 0x56, 0x00, 0x96, 0x97, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd1, 0x03, 0x19,
	0xaa, 0x07, 0xd1, 0x13, 0x04, 0x95, 0x53, 0x72, 0xe2, 0xe2, 0x82, 0x88, 0xf8, 0xa4, 0xa6, 0x95,
	0x90, 0x69, 0x86, 0x1f, 0x97, 0x18, 0x44, 0xa4, 0xd8, 0x2f, 0x33, 0x39, 0xdb, 0x2f, 0x31, 0x37,
	0xd5, 0x39, 0x23, 0x31, 0x2f, 0x9d, 0x5c, 0x37, 0x25, 0xb1, 0x81, 0x03, 0xc1, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xce, 0x42, 0xfc, 0xbe, 0x1b, 0x01, 0x00, 0x00,
}
