// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Question/Question.proto

package Data_Question

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	Guid                 string    `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Type                 int32     `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Answers              []*Answer `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad8bad53674a2e81, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Question) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Question) GetAnswers() []*Answer {
	if m != nil {
		return m.Answers
	}
	return nil
}

func init() {
	proto.RegisterType((*Question)(nil), "Data.Question.Question")
}

func init() { proto.RegisterFile("Question/Question.proto", fileDescriptor_ad8bad53674a2e81) }

var fileDescriptor_ad8bad53674a2e81 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0f, 0x2c, 0x4d, 0x2d,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78, 0x5d,
	0x12, 0x4b, 0x12, 0xf5, 0x60, 0x82, 0x52, 0xa2, 0x70, 0x75, 0x8e, 0x79, 0xc5, 0xe5, 0xa9, 0x45,
	0x10, 0x55, 0x4a, 0xc9, 0x5c, 0x1c, 0x30, 0x09, 0x21, 0x21, 0x2e, 0x96, 0xf4, 0xd2, 0xcc, 0x14,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0x24, 0x56, 0x52, 0x59, 0x90, 0x2a, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66, 0x0b, 0xe9, 0x73, 0xb1, 0x27, 0x82, 0xcd, 0x28, 0x96,
	0x60, 0x56, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd5, 0x43, 0xb1, 0x4b, 0x0f, 0x62, 0x43, 0x10, 0x4c,
	0x55, 0x12, 0x1b, 0xd8, 0x2e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x28, 0xd2, 0xb1,
	0xac, 0x00, 0x00, 0x00,
}
