// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Messages client -> server
type JoinGame struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGame) Reset()         { *m = JoinGame{} }
func (m *JoinGame) String() string { return proto.CompactTextString(m) }
func (*JoinGame) ProtoMessage()    {}
func (*JoinGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *JoinGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGame.Unmarshal(m, b)
}
func (m *JoinGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGame.Marshal(b, m, deterministic)
}
func (m *JoinGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGame.Merge(m, src)
}
func (m *JoinGame) XXX_Size() int {
	return xxx_messageInfo_JoinGame.Size(m)
}
func (m *JoinGame) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGame.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGame proto.InternalMessageInfo

func (m *JoinGame) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// Messages server -> client
type GameJoined struct {
	GUID                 string    `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	Players              []*Player `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameJoined) Reset()         { *m = GameJoined{} }
func (m *GameJoined) String() string { return proto.CompactTextString(m) }
func (*GameJoined) ProtoMessage()    {}
func (*GameJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *GameJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameJoined.Unmarshal(m, b)
}
func (m *GameJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameJoined.Marshal(b, m, deterministic)
}
func (m *GameJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameJoined.Merge(m, src)
}
func (m *GameJoined) XXX_Size() int {
	return xxx_messageInfo_GameJoined.Size(m)
}
func (m *GameJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_GameJoined.DiscardUnknown(m)
}

var xxx_messageInfo_GameJoined proto.InternalMessageInfo

func (m *GameJoined) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *GameJoined) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type GameStart struct {
	GUID                 string    `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	Players              []*Player `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameStart) Reset()         { *m = GameStart{} }
func (m *GameStart) String() string { return proto.CompactTextString(m) }
func (*GameStart) ProtoMessage()    {}
func (*GameStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *GameStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStart.Unmarshal(m, b)
}
func (m *GameStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStart.Marshal(b, m, deterministic)
}
func (m *GameStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStart.Merge(m, src)
}
func (m *GameStart) XXX_Size() int {
	return xxx_messageInfo_GameStart.Size(m)
}
func (m *GameStart) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStart.DiscardUnknown(m)
}

var xxx_messageInfo_GameStart proto.InternalMessageInfo

func (m *GameStart) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *GameStart) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type GameUpdate struct {
	GUID                 string    `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	Players              []*Player `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players,omitempty"`
	Question             *Question `protobuf:"bytes,3,opt,name=Question,proto3" json:"Question,omitempty"`
	Time                 int32     `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameUpdate) Reset()         { *m = GameUpdate{} }
func (m *GameUpdate) String() string { return proto.CompactTextString(m) }
func (*GameUpdate) ProtoMessage()    {}
func (*GameUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *GameUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameUpdate.Unmarshal(m, b)
}
func (m *GameUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameUpdate.Marshal(b, m, deterministic)
}
func (m *GameUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameUpdate.Merge(m, src)
}
func (m *GameUpdate) XXX_Size() int {
	return xxx_messageInfo_GameUpdate.Size(m)
}
func (m *GameUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_GameUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_GameUpdate proto.InternalMessageInfo

func (m *GameUpdate) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *GameUpdate) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameUpdate) GetQuestion() *Question {
	if m != nil {
		return m.Question
	}
	return nil
}

func (m *GameUpdate) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GameWait struct {
	GUID                 string   `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameWait) Reset()         { *m = GameWait{} }
func (m *GameWait) String() string { return proto.CompactTextString(m) }
func (*GameWait) ProtoMessage()    {}
func (*GameWait) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *GameWait) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameWait.Unmarshal(m, b)
}
func (m *GameWait) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameWait.Marshal(b, m, deterministic)
}
func (m *GameWait) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameWait.Merge(m, src)
}
func (m *GameWait) XXX_Size() int {
	return xxx_messageInfo_GameWait.Size(m)
}
func (m *GameWait) XXX_DiscardUnknown() {
	xxx_messageInfo_GameWait.DiscardUnknown(m)
}

var xxx_messageInfo_GameWait proto.InternalMessageInfo

func (m *GameWait) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

type NextQuestion struct {
	GUID                 string    `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	Question             *Question `protobuf:"bytes,2,opt,name=Question,proto3" json:"Question,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NextQuestion) Reset()         { *m = NextQuestion{} }
func (m *NextQuestion) String() string { return proto.CompactTextString(m) }
func (*NextQuestion) ProtoMessage()    {}
func (*NextQuestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *NextQuestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextQuestion.Unmarshal(m, b)
}
func (m *NextQuestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextQuestion.Marshal(b, m, deterministic)
}
func (m *NextQuestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextQuestion.Merge(m, src)
}
func (m *NextQuestion) XXX_Size() int {
	return xxx_messageInfo_NextQuestion.Size(m)
}
func (m *NextQuestion) XXX_DiscardUnknown() {
	xxx_messageInfo_NextQuestion.DiscardUnknown(m)
}

var xxx_messageInfo_NextQuestion proto.InternalMessageInfo

func (m *NextQuestion) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *NextQuestion) GetQuestion() *Question {
	if m != nil {
		return m.Question
	}
	return nil
}

type GameEnd struct {
	GUID                 string   `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameEnd) Reset()         { *m = GameEnd{} }
func (m *GameEnd) String() string { return proto.CompactTextString(m) }
func (*GameEnd) ProtoMessage()    {}
func (*GameEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *GameEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEnd.Unmarshal(m, b)
}
func (m *GameEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEnd.Marshal(b, m, deterministic)
}
func (m *GameEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEnd.Merge(m, src)
}
func (m *GameEnd) XXX_Size() int {
	return xxx_messageInfo_GameEnd.Size(m)
}
func (m *GameEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEnd.DiscardUnknown(m)
}

var xxx_messageInfo_GameEnd proto.InternalMessageInfo

func (m *GameEnd) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

type GameResult struct {
	GUID                 string   `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResult) Reset()         { *m = GameResult{} }
func (m *GameResult) String() string { return proto.CompactTextString(m) }
func (*GameResult) ProtoMessage()    {}
func (*GameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7}
}

func (m *GameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResult.Unmarshal(m, b)
}
func (m *GameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResult.Marshal(b, m, deterministic)
}
func (m *GameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResult.Merge(m, src)
}
func (m *GameResult) XXX_Size() int {
	return xxx_messageInfo_GameResult.Size(m)
}
func (m *GameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameResult proto.InternalMessageInfo

func (m *GameResult) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func init() {
	proto.RegisterType((*JoinGame)(nil), "message.JoinGame")
	proto.RegisterType((*GameJoined)(nil), "message.GameJoined")
	proto.RegisterType((*GameStart)(nil), "message.GameStart")
	proto.RegisterType((*GameUpdate)(nil), "message.GameUpdate")
	proto.RegisterType((*GameWait)(nil), "message.GameWait")
	proto.RegisterType((*NextQuestion)(nil), "message.NextQuestion")
	proto.RegisterType((*GameEnd)(nil), "message.GameEnd")
	proto.RegisterType((*GameResult)(nil), "message.GameResult")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95,
	0xe2, 0x29, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x82, 0x08, 0x4b, 0xf1, 0x15, 0x96, 0xa6, 0x16, 0x97,
	0x64, 0xe6, 0xe7, 0x41, 0xf8, 0x4a, 0xc6, 0x5c, 0x1c, 0x5e, 0xf9, 0x99, 0x79, 0xee, 0x89, 0xb9,
	0xa9, 0x42, 0xea, 0x5c, 0x6c, 0x01, 0x60, 0xb5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xfc,
	0x7a, 0x50, 0x33, 0xf4, 0x20, 0xc2, 0x41, 0x50, 0x69, 0x25, 0x6f, 0x2e, 0x2e, 0x90, 0x06, 0x90,
	0xc6, 0xd4, 0x14, 0x21, 0x21, 0x2e, 0x16, 0xf7, 0x50, 0x4f, 0x17, 0xb0, 0x26, 0xce, 0x20, 0x30,
	0x5b, 0x48, 0x93, 0x8b, 0x1d, 0xa2, 0xb6, 0x58, 0x82, 0x49, 0x81, 0x19, 0x9b, 0x59, 0x30, 0x79,
	0x25, 0x2f, 0x2e, 0x4e, 0x90, 0x61, 0xc1, 0x25, 0x89, 0x45, 0x25, 0x94, 0x9a, 0xd5, 0xc7, 0x08,
	0x71, 0x59, 0x68, 0x41, 0x4a, 0x62, 0x49, 0x2a, 0x85, 0xa6, 0x09, 0xe9, 0x72, 0x71, 0x04, 0x42,
	0x43, 0x4b, 0x82, 0x19, 0x1c, 0x22, 0x82, 0x70, 0xb5, 0x30, 0x89, 0x20, 0xb8, 0x12, 0x90, 0x6d,
	0x21, 0x99, 0xb9, 0xa9, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x92, 0x1c, 0x17,
	0x07, 0xc8, 0x3d, 0xe1, 0x89, 0x99, 0x58, 0xfd, 0xa6, 0x14, 0xc8, 0xc5, 0xe3, 0x97, 0x5a, 0x51,
	0x82, 0x6c, 0x06, 0x86, 0x8b, 0x91, 0x9d, 0xc1, 0x44, 0xd0, 0x19, 0x4a, 0xb2, 0x5c, 0xec, 0x20,
	0x2b, 0x5d, 0xf3, 0xb0, 0xc6, 0x8c, 0x92, 0x02, 0x24, 0x84, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0xb0,
	0xba, 0x29, 0x89, 0x0d, 0x9c, 0x32, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x45, 0x93,
	0xb7, 0x4e, 0x02, 0x00, 0x00,
}
