// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quiz.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Quiz struct {
	Guid                 string      `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Questions            []*Question `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Quiz) Reset()         { *m = Quiz{} }
func (m *Quiz) String() string { return proto.CompactTextString(m) }
func (*Quiz) ProtoMessage()    {}
func (*Quiz) Descriptor() ([]byte, []int) {
	return fileDescriptor_93138adfabfb5582, []int{0}
}

func (m *Quiz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quiz.Unmarshal(m, b)
}
func (m *Quiz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quiz.Marshal(b, m, deterministic)
}
func (m *Quiz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quiz.Merge(m, src)
}
func (m *Quiz) XXX_Size() int {
	return xxx_messageInfo_Quiz.Size(m)
}
func (m *Quiz) XXX_DiscardUnknown() {
	xxx_messageInfo_Quiz.DiscardUnknown(m)
}

var xxx_messageInfo_Quiz proto.InternalMessageInfo

func (m *Quiz) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Quiz) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Quiz) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

func init() {
	proto.RegisterType((*Quiz)(nil), "message.Quiz")
}

func init() { proto.RegisterFile("quiz.proto", fileDescriptor_93138adfabfb5582) }

var fileDescriptor_93138adfabfb5582 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2c, 0xcd, 0xac,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95,
	0xe2, 0x2b, 0x2c, 0x4d, 0x2d, 0x2e, 0xc9, 0xcc, 0xcf, 0x83, 0x48, 0x28, 0xc5, 0x73, 0xb1, 0x04,
	0x96, 0x66, 0x56, 0x09, 0x09, 0x71, 0xb1, 0xa4, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x88, 0x18, 0x88, 0x2d,
	0xa4, 0xcf, 0xc5, 0x09, 0x33, 0xa1, 0x58, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x50, 0x0f,
	0x6a, 0xb8, 0x5e, 0x20, 0x54, 0x26, 0x08, 0xa1, 0x26, 0x89, 0x0d, 0x6c, 0x8f, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x73, 0x13, 0xed, 0xbc, 0x8e, 0x00, 0x00, 0x00,
}
