// Code generated by protoc-gen-go. DO NOT EDIT.
// source: screen.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScreenLayout struct {
	//JSON string
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScreenLayout) Reset()         { *m = ScreenLayout{} }
func (m *ScreenLayout) String() string { return proto.CompactTextString(m) }
func (*ScreenLayout) ProtoMessage()    {}
func (*ScreenLayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_b79f3b69cf8c7563, []int{0}
}

func (m *ScreenLayout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScreenLayout.Unmarshal(m, b)
}
func (m *ScreenLayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScreenLayout.Marshal(b, m, deterministic)
}
func (m *ScreenLayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScreenLayout.Merge(m, src)
}
func (m *ScreenLayout) XXX_Size() int {
	return xxx_messageInfo_ScreenLayout.Size(m)
}
func (m *ScreenLayout) XXX_DiscardUnknown() {
	xxx_messageInfo_ScreenLayout.DiscardUnknown(m)
}

var xxx_messageInfo_ScreenLayout proto.InternalMessageInfo

func (m *ScreenLayout) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SwitchScreen struct {
	Layout               *ScreenLayout `protobuf:"bytes,1,opt,name=Layout,proto3" json:"Layout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SwitchScreen) Reset()         { *m = SwitchScreen{} }
func (m *SwitchScreen) String() string { return proto.CompactTextString(m) }
func (*SwitchScreen) ProtoMessage()    {}
func (*SwitchScreen) Descriptor() ([]byte, []int) {
	return fileDescriptor_b79f3b69cf8c7563, []int{1}
}

func (m *SwitchScreen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchScreen.Unmarshal(m, b)
}
func (m *SwitchScreen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchScreen.Marshal(b, m, deterministic)
}
func (m *SwitchScreen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchScreen.Merge(m, src)
}
func (m *SwitchScreen) XXX_Size() int {
	return xxx_messageInfo_SwitchScreen.Size(m)
}
func (m *SwitchScreen) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchScreen.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchScreen proto.InternalMessageInfo

func (m *SwitchScreen) GetLayout() *ScreenLayout {
	if m != nil {
		return m.Layout
	}
	return nil
}

func init() {
	proto.RegisterType((*ScreenLayout)(nil), "message.ScreenLayout")
	proto.RegisterType((*SwitchScreen)(nil), "message.SwitchScreen")
}

func init() { proto.RegisterFile("screen.proto", fileDescriptor_b79f3b69cf8c7563) }

var fileDescriptor_b79f3b69cf8c7563 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2e, 0x4a,
	0x4d, 0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0x55, 0xd2, 0xe0, 0xe2, 0x09, 0x06, 0x4b, 0xf8, 0x24, 0x56, 0xe6, 0x97, 0x96, 0x08, 0x49,
	0x70, 0xb1, 0x3b, 0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xc1, 0xb8, 0x4a, 0xb6, 0x5c, 0x3c, 0xc1, 0xe5, 0x99, 0x25, 0xc9, 0x19, 0x10, 0xf5, 0x42, 0xba,
	0x5c, 0x6c, 0x10, 0x3d, 0x60, 0x85, 0xdc, 0x46, 0xa2, 0x7a, 0x50, 0x33, 0xf5, 0x90, 0x0d, 0x0c,
	0x82, 0x2a, 0x4a, 0x62, 0x03, 0x5b, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x4b, 0xa8,
	0x65, 0x88, 0x00, 0x00, 0x00,
}
