// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinServer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinServer) Reset()         { *m = JoinServer{} }
func (m *JoinServer) String() string { return proto.CompactTextString(m) }
func (*JoinServer) ProtoMessage()    {}
func (*JoinServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *JoinServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinServer.Unmarshal(m, b)
}
func (m *JoinServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinServer.Marshal(b, m, deterministic)
}
func (m *JoinServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinServer.Merge(m, src)
}
func (m *JoinServer) XXX_Size() int {
	return xxx_messageInfo_JoinServer.Size(m)
}
func (m *JoinServer) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinServer.DiscardUnknown(m)
}

var xxx_messageInfo_JoinServer proto.InternalMessageInfo

type ServerJoined struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerJoined) Reset()         { *m = ServerJoined{} }
func (m *ServerJoined) String() string { return proto.CompactTextString(m) }
func (*ServerJoined) ProtoMessage()    {}
func (*ServerJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ServerJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerJoined.Unmarshal(m, b)
}
func (m *ServerJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerJoined.Marshal(b, m, deterministic)
}
func (m *ServerJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerJoined.Merge(m, src)
}
func (m *ServerJoined) XXX_Size() int {
	return xxx_messageInfo_ServerJoined.Size(m)
}
func (m *ServerJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerJoined.DiscardUnknown(m)
}

var xxx_messageInfo_ServerJoined proto.InternalMessageInfo

func (m *ServerJoined) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterType((*JoinServer)(nil), "message.JoinServer")
	proto.RegisterType((*ServerJoined)(nil), "message.ServerJoined")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0x95, 0xe2, 0x29, 0xc8, 0x49, 0xac, 0x84, 0x09, 0x2b, 0xf1, 0x70, 0x71, 0x79, 0xe5, 0x67,
	0xe6, 0x05, 0x83, 0x95, 0x2a, 0x99, 0x73, 0xf1, 0x40, 0x58, 0x20, 0xb1, 0xd4, 0x14, 0x21, 0x75,
	0x2e, 0xb6, 0x00, 0xb0, 0x6a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x7e, 0x3d, 0xa8, 0x29,
	0x7a, 0x10, 0xe1, 0x20, 0xa8, 0x74, 0x12, 0x1b, 0xd8, 0x34, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x43, 0x77, 0x89, 0xad, 0x74, 0x00, 0x00, 0x00,
}
